### ISSUE TITLE
New Hope FFTs

### ISSUE THREAD

**Issue by rabinabo** [vscrypto/ringlwe#1]
I've been looking at New Hope for my company, so I've been testing your code, specifically rlwe_1024_12289_binomial. I noticed that the FFTs that it uses, FFT_twisted_forward_1024_12289 and FFT_twisted_backward_1024_12289 are not inverses of each other, multiplying everything by a factor of 1024.  Did you forget to divide by 1024 (or m, really) at the end?

When I run your code, the key agreement seems to work. When I try to simulate the same functions in sage though, that constant factor increases the error terms, making the key agreement fail.

Thanks,
Rino

**Comment by rabinabo** [comment]
@vscrypto I was wondering if you saw this question.

**Comment by vscrypto** [comment]
Hi Rino

Thank you for your comment. Please note that the key agreement only uses FFT_forward and FFT_backward. These are defined in rlwe_includes.h in terms of their twisted versions and a division by 1024 (implemented as a multiplication by 12277, which is the inverse of 1024 modulo 12289):

	/*Use the twisted Fourier Transform in the Power of 2 case for multiplication
	in the ring F_q[x] / <x^m+1>*/
	
	#define FFT_forward FFT_twisted_forward_1024_12289
	#define FFT_backward(_x)\
	do {\
		FFT_twisted_backward_1024_12289(_x);\
		for (uint16_t _i = 0; _i < m; ++_i) {\
			MUL_MOD((_x)[_i], (_x)[_i], 12277, (q));\
		}\
	} while(0)

I wish you the best with testing the code.

Best Regards

Vikram

**Comment by rabinabo** [comment]
Thanks for the response, I completely missed that section of the code.  I had implemented the code in sage, but didn't see that bit.

Best wishes,
Rino
